### ISSUE TITLE
Bug in calling array.dim_list.__getitem__()

### ISSUE THREAD

**Issue by ryhuff** [MadAlex1997/NuMojo#5]
Hello,

First off, thanks for taking on the project of making Mojo's version of Numpy! For the issue I'm seeing, there seems to be something going on when calling the `array.dim_list.__getitem__()` method for the `ndarray` implementation. After calling the function once, the next call balloons to a large number (ex. in my case 1.4e14). This becomes extremely problematic when calling the `array.arr_print()` function as the loop is now out of bounds for the size of the array. Below is the code I used to created the issue:

```
from ndarray.arraynd import Array
alias array = Array[DType.float64, 4]
let f64funcs = array()

var x = f64funcs .zeros(10)

print(x.size) # -> 10

print(x.tshape[0], x.tshape[1]) # -> 10, 0

# first call to __getitem__
print(x.dim_list[0]) # -> 1

# second call to __getitem__
print(x.dim_list[0]) # -> 140378715213677

# third call to __getitem__
print(x.dim_list[0]) # -> 140378715213677
```

I'm not sure if this is an issue with the VariadicList during initialization or during each function call, or something else. I know this package is in its infancy, but I just wanted to bring this to your attention.

Thank you for your time and please let me know if there's any additional information you need. (First time submitting one of these!)

**Comment by MadAlex1997** [comment]
Okay, so I think there is an issue with variadic lists in the REPL and maybe the Jupyter Kernal. When I call your code from a file (mojo err.mojo) it works like I would expect. But if I call a variadic list at all in the REPL it gives weird answers like it calling random locations in the memory.

Where are you using it from: mojo interactive, Jupyter, or running the file with the mojo command? I will note that I have only tested it in the form of the mojo file.mojo method of running things.

**Comment by MadAlex1997** [comment]
Ok so this issue goes away when the things are in a function, which is a known general problem for Mojo.

I'll leave this open for now so if others have the same question they can see it.

**Solution:**
Run everything inside of a function rather than the outermost context.
